version: '3.7'

services:
  timemachine:
    image: odarriba/timemachine:latest
    restart: unless-stopped
    networks:
      - timemachine
    volumes:
      - /data/backups/timemachine:/timemachine
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - 548:548/tcp
      - 636:636/tcp
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"

networks:
  timemachine:
    