version: '3.7'

services:
  timemachine:
    build: .
    container_name: timemachine
    restart: unless-stopped
    env_file:
      - users.env
    networks:
      - timemachine
    volumes:
      - ./backups:/backups
    ports:
      - 445:445/tcp
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"

networks:
  timemachine:
    