version: '3.7'

services:
  timemachine:
    build: .
    container_name: timemachine
    restart: unless-stopped
    environment:
      USER_HPLOEG: hploeg
      PASSWORD_HPLOEG: hploeg
    networks:
      - timemachine
    volumes:
      - ./backups:/backups
    ports:
      - 445:445/tcp
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"

networks:
  timemachine:
    